on: 
  workflow_dispatch:
    inputs:
      who-to-greet:  # id of input
        description: 'Who to greet'
        default: "IGWE"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - if: ${{ who-to-greet == true }}
        run: echo "The script can run"
      - id: foo
        uses: judeigwe/gh-composite-actions@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
