on: 
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: judeigwe/gh-composite-actions@v1.1
        with:
          who-to-greet: ${{ secret.WHO_TO_GREET }}
